---
- hosts: LAMPServer
  become: true
  become_user: root

  tasks:
    - name: install pip
      apt: name=python-pip state=present

    - name: install libmysqlclient-dev
      apt: name=libmysqlclient-dev state=present

    - name: install the Python MYSQLDB module
      pip: name=MySQL-python

    - name: Create database user kvanderp
      mysql_user: user=kvanderp password=password priv=*.*:ALL state=present

    - name: Create database f5
      mysql_db: db=f5 state=present

    - name: Create a table reg
      command: mysql -ukvanderp -ppassword -e 'CREATE TABLE reg (name varchar(30),email varchar(30),user varchar(30),pass varchar(30));' f5
